# Create a program that will play the “cows and bulls” game with the user. The game works like this:

# Randomly generate a 4-digit number. Ask the user to guess a 4-digit number(Digits should not be repeated). For every digit that the user guessed correctly in the correct place, they have a “cow”. For every digit the user guessed correctly in the wrong place is a “bull.” Every time the user makes a guess, tell them how many “cows” and “bulls” they have. Once the user guesses the correct number, the game is over. Keep track of the number of guesses the user makes throughout teh game and tell the user at the end.

# Say the number generated by the computer is 1038. An example interaction could look like this:

#   Welcome to the Cows and Bulls Game! 
#   Enter a number: 
#   >>> 1234
#   2 cows, 0 bulls
#   >>> 1250
#   1 cow, 1 bull
#   ...
# Until the user guesses the number.

import random

def cows_and_bulls_game():
    """Play the Cows and Bulls game."""
    print("Welcome to the Cows and Bulls Game!")
    
    # Generate a random 4-digit number with unique digits
    secret_number = generate_number()
    attempts = 0

    while True:
        guess = input("Enter a 4-digit number (digits should not be repeated): ")
        if guess.lower() == 'q':
            print(f"Secret number is - {secret_number} \nThanks for playing!")
            break
        
        # Validate input
        if len(guess) != 4 or not guess.isdigit() or len(set(guess)) != 4:
            print("Invalid input. Please enter a 4-digit number with unique digits.")
            continue
        
        attempts += 1
        cows, bulls = calculate_cows_and_bulls(secret_number, guess)
        
        if cows == 4:
            print(f"Congratulations! You've guessed the number {secret_number} in {attempts} attempts.")
            break
        else:
            print(f"{cows} cow(s), {bulls} bull(s)")



def calculate_cows_and_bulls(secret, guess):
    """Calculate the number of cows and bulls."""
    cows = sum(s == g for s, g in zip(secret, guess))
    bulls = sum(min(secret.count(d), guess.count(d)) for d in set(guess)) - cows
    return cows, bulls


def generate_number():
    """Generate a random 4-digit number with unique digits."""
    while True:
        number = str(random.randint(1000, 9999))
        if len(set(number)) == 4:  # Check for unique digits
            return number
        
if __name__ == "__main__":
    cows_and_bulls_game()
    